version: 0.0
os: linux
Files:
  - source: /
    destination: /opt/my-app
Permissions:
  - object: /opt/my-app
    pattern: "**"
    owner: nodeapp
    group: nodeapp
    mode: 755
    type:
      - directory
  - object: /opt/my-app
    pattern: "**"
    owner: nodeapp
    group: nodeapp
    mode: 644
    type:
      - file
Hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 300
      runas: root